#!/usr/bin/env ruby

require File.dirname(__FILE__) + '/config/environment'

CONFIG = YAML::load(File.read('./config/config.yml'))['xplanner']

endpoint = CONFIG['endpoint']
username = CONFIG['username']
password = CONFIG['password']

driver = XPlanner.new
driver.options["protocol.http.basic_auth"] << [endpoint, username, password]

iteration = driver.getCurrentIteration(CONFIG['project_id'])
stories = driver.getUserStories(iteration.id)

Prawn::Document.generate_cards("cards.pdf", stories)



